production:
  adapter: postgresql
  database: ENV['DB_NAME']
  username: ENV['DB_USER']
  password: ENV['DB_PASS']
  post: 5432
  encoding: unicode



staging:
  adapter: postgresql
  database: ENV['DB_NAME']
  username: ENV['DB_USER']
  password: ENV['DB_PASS']
  post: 5432
  encoding: unicode

development:
  adapter: postgresql
  database: batterypop_v2_development
  host: localhost
  post: 5432
  encoding: unicode