require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EpisodesController do

  # This should return the minimal set of attributes required to create a valid
  # Episode. As you add validations to Episode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EpisodesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all episodes as @episodes" do
      episode = Episode.create! valid_attributes
      get :index, {}, valid_session
      assigns(:episodes).should eq([episode])
    end
  end

  describe "GET show" do
    it "assigns the requested episode as @episode" do
      episode = Episode.create! valid_attributes
      get :show, {:id => episode.to_param}, valid_session
      assigns(:episode).should eq(episode)
    end
  end

  describe "GET new" do
    it "assigns a new episode as @episode" do
      get :new, {}, valid_session
      assigns(:episode).should be_a_new(Episode)
    end
  end

  describe "GET edit" do
    it "assigns the requested episode as @episode" do
      episode = Episode.create! valid_attributes
      get :edit, {:id => episode.to_param}, valid_session
      assigns(:episode).should eq(episode)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Episode" do
        expect {
          post :create, {:episode => valid_attributes}, valid_session
        }.to change(Episode, :count).by(1)
      end

      it "assigns a newly created episode as @episode" do
        post :create, {:episode => valid_attributes}, valid_session
        assigns(:episode).should be_a(Episode)
        assigns(:episode).should be_persisted
      end

      it "redirects to the created episode" do
        post :create, {:episode => valid_attributes}, valid_session
        response.should redirect_to(Episode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved episode as @episode" do
        # Trigger the behavior that occurs when invalid params are submitted
        Episode.any_instance.stub(:save).and_return(false)
        post :create, {:episode => { "title" => "invalid value" }}, valid_session
        assigns(:episode).should be_a_new(Episode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Episode.any_instance.stub(:save).and_return(false)
        post :create, {:episode => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested episode" do
        episode = Episode.create! valid_attributes
        # Assuming there are no other episodes in the database, this
        # specifies that the Episode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Episode.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => episode.to_param, :episode => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested episode as @episode" do
        episode = Episode.create! valid_attributes
        put :update, {:id => episode.to_param, :episode => valid_attributes}, valid_session
        assigns(:episode).should eq(episode)
      end

      it "redirects to the episode" do
        episode = Episode.create! valid_attributes
        put :update, {:id => episode.to_param, :episode => valid_attributes}, valid_session
        response.should redirect_to(episode)
      end
    end

    describe "with invalid params" do
      it "assigns the episode as @episode" do
        episode = Episode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Episode.any_instance.stub(:save).and_return(false)
        put :update, {:id => episode.to_param, :episode => { "title" => "invalid value" }}, valid_session
        assigns(:episode).should eq(episode)
      end

      it "re-renders the 'edit' template" do
        episode = Episode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Episode.any_instance.stub(:save).and_return(false)
        put :update, {:id => episode.to_param, :episode => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested episode" do
      episode = Episode.create! valid_attributes
      expect {
        delete :destroy, {:id => episode.to_param}, valid_session
      }.to change(Episode, :count).by(-1)
    end

    it "redirects to the episodes list" do
      episode = Episode.create! valid_attributes
      delete :destroy, {:id => episode.to_param}, valid_session
      response.should redirect_to(episodes_url)
    end
  end

end
